# Variables
FRONTEND_DIR := ./frontend
BACKEND_DIR := ./backend

# Define the default target
.PHONY: all
all: run

# update all libraries
.PHONY: update
update:
	@echo "Updating all libraries..."
	@cd $(BACKEND_DIR) && go mod tidy && cd .. && cd $(FRONTEND_DIR) && npm install

# Backend target
.PHONY: run-backend
run-backend:
	@echo "Running Go backend..."
	@cd $(BACKEND_DIR) && go mod tidy && go run main.go types.go server.go userHandler.go lobbyHandler.go

# Frontend target
.PHONY: run-frontend
run-frontend:
	@echo "Running React frontend..."
	@cd $(FRONTEND_DIR) && npm install && npm start

# Run both backend and frontend simultaneously
.PHONY: run
run:
	@echo "Starting both backend and frontend..."
	@make -j2 run-backend run-frontend